### ISSUE TITLE
render_table without SQL-Alchemy and Action URLs

### ISSUE THREAD

**Issue by Markus-** [helloflask/bootstrap-flask#268]
Hi,

I tried to render a table with row-specific URLs without using a Model.
As I understand the code, the problem is, that if I use a string as URL it is more or less static. When I want to create a dynamic (row specific) url I need to hand over a Model (which I do not have).

I just use a JSON-Object as data and a dict as titles.

```python
    products = requests.get("http://localhost:3000/product").json()
    titles = [('name', 'Product'),('long_name', 'Produkt Lang Name')]

    return render_template('products/index.html', products = products, titles = titles)
```

Without any action urls the rendering works as expected.
```python
        {{ render_table(products, titles, primary_key='name', show_actions=True, custom_actions=[('Run', 'play-fill', 'modals')]) }}
```

Any idea how to add something dynamic?
```python
... 'modals/' + row[0] + '/edit'
```

Thanks 
Markus

**Comment by PanderMusubi** [comment]
I think the current implementation does not support that, but you might handle it inside the implementation of the supported action urls. By looking at the values passed, either forward to the desired URL or call the appropriate method in there (with some if-elif-elif-else). Does that help you?

**Comment by nickovs** [comment]
I ran into the same issue, so I looked into the code for the `render_table()` macro. Fixing this is pretty straightforward and in fact I've hacked a version for myself that allows actions on dicts and non-model objects.

The issue is that the internal macro [`build_url()`](https://github.com/helloflask/bootstrap-flask/blob/9b066cba7b21d4c229a9818837fcd7b12695ddaf/flask_bootstrap/templates/base/table.html#L4-L26) that is used to build the action link URLs takes a very odd approach to finding the fields to be inserted into the link. All the calls to this macro are inside [the loop](https://github.com/helloflask/bootstrap-flask/blob/9b066cba7b21d4c229a9818837fcd7b12695ddaf/flask_bootstrap/templates/base/table.html#L81) that iterates over the rows, but rather than passing the `row` itself into the macro, it passes the model class and the primary key for the current row and then fetches the record all over again **for every action** while building the links.

Not only does this break the support for actions on non-SQLAlchemy records, but it also means that there are up to an extra 3 database queries for every row, despite the data already being there.

My quick hack this evening just changed the URL building macro from `build_url(endpoint, model, pk, url_tuples) ` to `build_url(record, endpoint, url_tuples)`, stripped out the lookup of the record with `model.query.get(pk)` and then fixed the four calls to the function to pass the `row` variable instead of the model and primary key.

This fix seems to work for my needs, although this is the first time I've looked at the `bootstrap-flask` code so there may be edge cases I'm not aware of. I will try to package this up as a PR and submit it, but that might need to wait until the weekend.

**Comment by PanderMusubi** [comment]
Thanks, but reopening for Nick's PR.

**Comment by Markus-** [comment]
Sorry for this. I am new to PR / Issue Handling.

**Comment by PanderMusubi** [comment]
No worries. 😃

**Comment by PanderMusubi** [comment]
I will let @greyli answer this first. Adding optional parameters is never a problem, breaking the API if we can't avoid it we can talk about and could result in a version 3 e.g., especially if the implementation is faster.
